x-common-env: &common-env
  DATABASE_URL: postgres://dataengineeringuser:dataengineeringpwd@db:5432/dataengineeringdb
  KAGGLE_API_TOKEN: KGAT_7ec727d8cbc61e4e1927a849a122fbbd
  API_URL: http://api:3000
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_DB: dataengineeringdb
  POSTGRES_USER: dataengineeringuser
  POSTGRES_PASSWORD: dataengineeringpwd

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dataengineeringuser
      POSTGRES_PASSWORD: dataengineeringpwd
      POSTGRES_DB: dataengineeringdb
      ENVIRONMENT: ${ENVIRONMENT:-development}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  metabase:
    image: metabase/metabase:latest
    volumes:
      - ./metabasedata:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    ports:
      - "3001:3000"
    depends_on:
      - db

  api:
    build: ./apidocker
    ports:
      - "3000:3000"
    volumes:
      - ./apidocker/src:/app/src
      - ./simdata:/data/simdata
    working_dir: /app
    environment:
      SIMDATA_FOLDER: /data/simdata

  app:
    build: ./appdocker
    profiles: ["dev"]
    volumes:
      - ./appdocker:/app
      - ./rawdata:/data/rawdata
      - ./simdata:/data/simdata
      - ./tmpdata:/data/tmpdata
      - ./cleandata:/data/cleandata
    working_dir: /app/src
    environment:
      LANDING_ZONE: /data/rawdata
      SIMDATA_FOLDER: /data/simdata
      TEMP_EXTRACT_ZONE: /data/tmpdata
      CLEAN_DATA_ZONE: /data/cleandata
      <<: *common-env

    command: tail -f /dev/null
    depends_on:
      - db
      - api

  airflow:
    image: apache/airflow:2.7.1
    profiles: ["prod"]
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflowuser:airflowpwd@db:5432/airflowdb
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflowuser:airflowpwd@db:5432/airflowdb
      AIRFLOW__DATABASE__ALCHEMY_CONN: postgresql+psycopg2://airflowuser:airflowpwd@db:5432/airflowdb
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
      LANDING_ZONE: /opt/airflow/data/rawdata
      SIMDATA_FOLDER: /opt/airflow/data/simdata
      TEMP_EXTRACT_ZONE: /opt/airflow/data/tmpdata
      CLEAN_DATA_ZONE: /opt/airflow/data/cleandata
      <<: *common-env
    ports:
      - "8080:8080"
    volumes:
      - ./appdag/entrypoint.sh:/opt/airflow/entrypoint.sh
      - ./appdag/dags:/opt/airflow/dags
      - ./appdag/logs:/opt/airflow/logs
      - ./appdag/plugins:/opt/airflow/plugins
      - ./appdocker/src:/opt/airflow/appsrc
      - ./appdocker/requirements.txt:/opt/airflow/requirements.txt
      - ./rawdata:/opt/airflow/data/rawdata
      - ./simdata:/opt/airflow/data/simdata
      - ./tmpdata:/opt/airflow/data/tmpdata
      - ./cleandata:/opt/airflow/data/cleandata
    depends_on:
      - db
      - api
    entrypoint: ["/bin/bash", "/opt/airflow/entrypoint.sh"]
